name: pull-request

on:
  - push
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn ci
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: x
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn build
